EVEREST-451 404 page
percona/percona-everest-frontend pull request #118
Opened 2023-10-05 09:47 UTC by filipmikes1

2023-10-11 14:40 UTC, fabio-silva requested changes

2023-10-11 14:40 UTC, fabio-silva commented on apps/everest/everest.app-root.tsx
>    },
why do we use the same route twice?

2023-10-11 14:40 UTC, fabio-silva commented on apps/everest/pages/404/NoMatch.tsx
> +  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
I think something's not right here. A laptop is `up("lg")`.
Also, `isLaptop` will return true for mobile resolution, because it's below "lg"

2023-10-11 14:40 UTC, fabio-silva commented on apps/everest/pages/404/NoMatch.tsx
> +          sx={{
aren't we using any variant?

2023-10-11 14:40 UTC, fabio-silva commented on apps/everest/pages/backups/backups.tsx
> +  useEffect(() => {
Why are we showing a 404 on the backups page?
If the user tries to play funny and insert a non-existent dbCluster, we just show empty data.

2023-10-11 14:40 UTC, fabio-silva commented on apps/everest/pages/cluster-overview/cluster-overview.tsx
> +  const { combinedDataForTable, loadingAllClusters } = useDbClusters();
what's this logic for?

2023-10-11 14:40 UTC, fabio-silva commented on ui-lib/icons/no-match/no-match.docs.mdx
> +import { NoMatch } from './no-match';
can be removed

2023-10-12 12:24 UTC, filipmikes1 commented on apps/everest/pages/backups/backups.tsx
> +  useEffect(() => {
Is it really behavior we want? I remember that in PMM this was considered as a bug.

2023-10-12 12:26 UTC, filipmikes1 commented on apps/everest/pages/cluster-overview/cluster-overview.tsx
> +  const { combinedDataForTable, loadingAllClusters } = useDbClusters();
Because without it when a user added a non-existent URL it showed an error notification. But maybe it is an overkill to optimize for non-existing URLs...

2023-10-12 12:29 UTC, filipmikes1 commented on apps/everest/pages/404/NoMatch.tsx
> +  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
Laptop is `up 'lg'`? I think that on other code in our app laptop is between mobile and desktop. And I am counting on it to be true for mobile as well that is why I have logic like this: `isLaptop ? (isMobile ? '13px' : '58px') : '150px',`

2023-10-12 12:31 UTC, filipmikes1 commented on apps/everest/everest.app-root.tsx
>    },
When I was testing it. It wasn't showing properly without second route in children array but I can recheck

2023-10-12 14:37 UTC, fabio-silva commented on apps/everest/pages/backups/backups.tsx
> +  useEffect(() => {
I think we'd better wait for Nuna and her input. The 404 page is specifically addressed for a non-existing web-address.
If we do it here, there will be a precedent and people will open bugs because here it's 404 and somewhere might not be. 
This said, let's wait for her return before we do something out of scope

2023-10-12 14:38 UTC, fabio-silva commented on apps/everest/pages/cluster-overview/cluster-overview.tsx
> +  const { combinedDataForTable, loadingAllClusters } = useDbClusters();
This is the same principle as before. Let's not change the logic until we define the correct view for empty data on sub URLs

2023-10-12 14:42 UTC, fabio-silva requested changes

2023-10-12 14:42 UTC, fabio-silva commented on apps/everest/everest.app-root.tsx
>    },
I see. Let me know if you need help, but in theory two 404 routes should not be needed

2023-10-19 12:08 UTC, filipmikes1 commented on apps/everest/everest.app-root.tsx
>    },
I removed the outside of children one. It was not necessary because the one in the children array caught everything and it can't be outside of children array because of the way we have it structured. Outside of children array it stoped showing menu bar.

2023-10-19 12:16 UTC, fabio-silva approved these changes

2023-10-20 08:34 UTC, merged