Everest 485 schedules in db wizard
percona/percona-everest-frontend pull request #134
Opened 2023-10-20 12:03 UTC by solovevayaroslavna

DRAFT

2023-11-14 11:13 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/backups/backups.tsx
> +    <Box sx={{ display: 'flex', flexDirection: 'column' }}>
// gap was removed because we haven't gaps in the other pages

2023-11-14 11:52 UTC, fabio-silva requested changes
@solovevayaroslavna can you confirm spacing between the toggle and the subtitle? It seems too close, not sure it's me

2023-11-15 04:18 UTC, solovevayaroslavna commented
@fabio-silva 
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/ea13216f-1aa7-425c-b9b9-2d2999a4a12c)

2023-11-15 23:03 UTC, fabio-silva requested changes

2023-11-15 23:03 UTC, fabio-silva commented on apps/everest/src/pages/database-form/database-preview/sections/advanced-configurations-section.tsx
> +import { AdvancedConfigurationType } from '../../database-form.schema.ts';
extension not needed.

2023-11-15 23:03 UTC, fabio-silva commented on apps/everest/src/pages/database-form/database-preview/sections/backups-section.tsx
> +import { BackupStepType } from '../../database-form.schema.ts';
same

2023-11-15 23:03 UTC, fabio-silva commented on apps/everest/src/pages/database-form/database-preview/sections/constants.ts
> +import { BackupsPreviewSection } from './backups-section.tsx';
same. There are others across the PR

2023-11-15 23:03 UTC, fabio-silva commented on apps/everest/src/pages/database-form/steps/backups/backups.schema.ts
> +import { ScheduleFormFields } from '../../../../components/schedule-form/schedule-form.types.ts';
let's use shorter paths, to make it more readable (i.e. components/)

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
> +              name: dbPayload?.scheduleName || `backup-${generateShortUID()}`,
In what usecase there can be no scheduleName available?

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
> +        name: dbPayload?.scheduleName || `backup-${generateShortUID()}`,
Same here

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/pages/database-form/steps/backups/schedule-section/schedule-section.tsx
> +import { ScheduleForm } from '../../../../../components/schedule-form/schedule-form.tsx';
You don't need to use relative paths anymore. Let's switch it to absolute paths.

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/components/schedule-form/schedule-form.tsx
> +      <AutoCompleteInput
Probably during merge you forgot to change this to AutoCompleteAutoFill component that autofills first option

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/pages/database-form/database-form.tsx
> +        console.log(errors);
Let's remove this console.log

2023-11-16 14:38 UTC, filipmikes1 commented on apps/everest/src/pages/database-form/steps/backups/backups.schema.ts
> +    if (backupsEnabled && !storageLocation) {
I think you have mistake here. Because with more than 1 schedules in db edit you cannot continue to next step after backups because it is still validating storageLocation field

2023-11-20 08:42 UTC, solovevayaroslavna commented on apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
> +              name: dbPayload?.scheduleName || `backup-${generateShortUID()}`,
dbWizard backup tab, case:
user choose PG db variant at the first step

I can modify validation schema before form was created, but I can't change schema itself by condition in the middle of the user filling.For PG we shouldn't allow backups so i allow to pass empty solution invalidation in case where user choose PG (but it's a temporary case, becouse after PG will be available we can remove it at all and we will always wait value there). I should was left a comment there =/

2023-11-20 08:44 UTC, solovevayaroslavna commented on apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
> +        name: dbPayload?.scheduleName || `backup-${generateShortUID()}`,
the same answer as in previous

2023-11-20 08:45 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/backups/schedule-section/schedule-section.tsx
> +import { ScheduleForm } from '../../../../../components/schedule-form/schedule-form.tsx';
it was automatically generated by my environment, so i hope we have a way to avoid it, but I already fixed it in all places

2023-11-20 08:48 UTC, solovevayaroslavna commented on apps/everest/src/components/schedule-form/schedule-form.tsx
> +      <AutoCompleteInput
thanks! I found it during test coverage, fixed and also cover with a test
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/aa121e0a-f4ad-41ee-973a-02fcfa69394a)
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/885c6745-ca1a-4e10-a38d-ba21f7d7d9b0)

2023-11-20 09:56 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/backups/backups.schema.ts
> +    if (backupsEnabled && !storageLocation) {
thanks! I missed it( we should have this validation only in shema "with schedules"

2023-11-20 09:56 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/backups/backups.schema.ts
> +    if (backupsEnabled && !storageLocation) {
fixed

2023-11-20 11:37 UTC, fabio-silva approved these changes

2023-11-20 13:26 UTC, filipmikes1 commented on apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
> +              name: dbPayload?.scheduleName || `backup-${generateShortUID()}`,
Okay I think I understand

2023-11-20 13:40 UTC, filipmikes1 approved these changes

2023-11-20 19:48 UTC, merged