EVEREST-600 Restore modal to db actions
percona/percona-everest-frontend pull request #186
Opened 2023-11-27 14:39 UTC by filipmikes1

https://jira.percona.com/browse/EVEREST-600

2023-11-30 11:13 UTC, fabio-silva commented on apps/everest/src/components/restore-db-modal/RestoreDbModal.tsx
> +        const backupNameStripped = data.backupList.split(' - ')[0];
given we're accessing [0], are we sure `split` is gonna return something?

2023-11-30 11:15 UTC, fabio-silva commented on apps/everest/src/components/restore-db-modal/RestoreDbModal.tsx
> +            renderValue(value) {
```suggestion
            renderValue: (value) => {
```

2023-11-30 11:18 UTC, fabio-silva commented on apps/everest/src/modals/ModalsWrapper.tsx
> +export const ModalsWrapper = () => {
can you further expand on what this component will do?

2023-11-30 11:22 UTC, fabio-silva commented on packages/ui-lib/src/form/inputs/radio/index.ts
> +export { RadioGroupProps };
Let's rename the files to "radio-group" instead of "radio"

2023-11-30 11:24 UTC, fabio-silva commented on packages/ui-lib/src/form/inputs/radio/radio.tsx
> +              checked={index === 0}
This `checked` probably should not be here. The initial value is to be defined in the default values coming from the form controller.

2023-12-01 09:04 UTC, filipmikes1 commented on apps/everest/src/components/restore-db-modal/RestoreDbModal.tsx
> +        const backupNameStripped = data.backupList.split(' - ')[0];
Yes, we are sure, because split function will return the whole original text if no delimiter is found

2023-12-01 09:08 UTC, filipmikes1 commented on apps/everest/src/modals/ModalsWrapper.tsx
> +export const ModalsWrapper = () => {
My idea is to add here all modals that will be used in multiple places. I just created this wrapper so they don't need to be directly in the Main file

2023-12-01 12:20 UTC, solovevayaroslavna commented on apps/everest/.e2e/db-restore/db-cluster-restore-action.e2e.ts
> +import { findDbAndClickRow } from '../utils/db-clusters-list';
```suggestion
import { findDbAndClickActions, findDbAndClickRow } from '../utils/db-clusters-list';
```

2023-12-01 12:20 UTC, solovevayaroslavna commented on apps/everest/.e2e/db-restore/db-cluster-restore-action.e2e.ts
> +    await restoreButton.click();
```suggestion
    await findDbAndClickActions(page, dbClusterName,'Restore from a backup');
```

2023-12-01 12:55 UTC, solovevayaroslavna requested changes

2023-12-01 12:56 UTC, solovevayaroslavna commented on apps/everest/.e2e/db-restore/db-cluster-restore-action.e2e.ts
> +    await restoreButton.click();
I checked tests locally with this, it works with this change

2023-12-05 09:46 UTC, filipmikes1 commented on apps/everest/.e2e/db-restore/db-cluster-restore-action.e2e.ts
> +    await restoreButton.click();
Thanks, I didn't notice this utility

2023-12-05 09:49 UTC, filipmikes1 commented on apps/everest/src/components/restore-db-modal/restoreDbModal.schema.ts
> +export type ScheduleFormData = z.infer<typeof schema>;
Good catch 👍 I copied it and didn't change it to the correct name

2023-12-05 09:55 UTC, filipmikes1 commented
> ![image](https://private-user-images.githubusercontent.com/90199600/287273652-9a69d080-cef3-488a-b6de-4ce2a534e722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Njk2ODMsIm5iZiI6MTcwMTc2OTM4MywicGF0aCI6Ii85MDE5OTYwMC8yODcyNzM2NTItOWE2OWQwODAtY2VmMy00ODhhLWI2ZGUtNGNlMmE1MzRlNzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWQyZmRhMWNmY2ZiMTlkYjI3ZTkwNWYwNTJhYmZlMTYxMmYzYmYyYjhkMjI5YjNkNGM5MWE0M2M3MTJiMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0GANCqMuaCehMKQQ9-fNZniWTEP65QGo15yPzI116V8)
> 
> also something strange with no value

This is default behavior by MUI select element when there is no menu items. I don't think we can do something about it.

2023-12-06 11:10 UTC, filipmikes1 commented on apps/everest/src/components/restore-db-modal/RestoreDbModal.tsx
> +              ml: '9px',
I asked Nuna and yes she approved this.

2023-12-07 14:28 UTC, solovevayaroslavna commented on apps/everest/src/modals/restore-db-modal/RestoreDbModal.tsx
> -            displayEmpty: true,
@fabio-silva why we need to remove this one?

2023-12-07 14:36 UTC, solovevayaroslavna approved these changes

2023-12-07 14:37 UTC, fabio-silva approved these changes

2023-12-07 14:53 UTC, merged