Everest 623 enable pitr for my sql
percona/percona-everest-frontend pull request #200
Opened 2023-12-13 10:46 UTC by solovevayaroslavna

[pitr-pg-db-create-mode.webm](https://github.com/percona/percona-everest-frontend/assets/90199600/df37ec84-b56f-4630-bfcd-9b8ca9e5aa85)

2023-12-14 15:15 UTC, fabio-silva requested changes

2023-12-14 15:15 UTC, fabio-silva commented on apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
> +    if (mode === 'new' && backupStorages?.length > 0) {
let's start with `if( backupStorages?.length > 0)` and do the remaining checks inside

2023-12-18 12:27 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
> +    if (mode === 'new' && backupStorages?.length > 0) {
fixed

2023-12-18 16:38 UTC, filipmikes1 requested changes

2023-12-18 16:38 UTC, filipmikes1 commented on apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
> +          autoCompleteProps={{
You probably don't need to add those props here, they should be already included in the AutoCompleteAutoFill component

2023-12-18 16:39 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
> +          autoCompleteProps={{
hmm. thanks. i'm going to check!

2023-12-18 17:10 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
> +          autoCompleteProps={{
fixed

2023-12-18 17:21 UTC, merged