EVEREST-691 Renamed password to token
percona/percona-everest-frontend pull request #203
Opened 2023-12-14 12:13 UTC by filipmikes1

2023-12-14 12:54 UTC, recharte requested changes

2023-12-14 12:54 UTC, recharte commented on apps/everest/src/pages/login/Login.messages.ts
> +    'Insert the token you have received during the installation in your terminal.',
```suggestion
    'Insert the authorization token you have received during the installation in your terminal.',
```

2023-12-14 12:54 UTC, recharte commented on apps/everest/src/pages/login/Login.messages.ts
> +  useTerminal: 'Use your terminal to reset your token.',
```suggestion
  useTerminal: 'Use your terminal to reset your authorization token.',
```

2023-12-15 11:55 UTC, fabio-silva approved these changes

2023-12-15 13:04 UTC, recharte approved these changes

2023-12-15 17:16 UTC, merged