EVEREST-762 Added support for single storage only
percona/percona-everest-frontend pull request #236
Opened 2024-01-22 10:45 UTC by filipmikes1

2024-01-22 23:32 UTC, fabio-silva requested changes

2024-01-22 23:32 UTC, fabio-silva commented on apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
> +      disableStorageSelection={!!dbClusterActiveStorage}
shouldn't this be only disabled for MongoDB?

2024-01-23 06:51 UTC, solovevayaroslavna commented on apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
> +      setValue(ScheduleFormFields.storageLocation, {
don't we need to trigger validation in this place?

2024-01-23 09:41 UTC, filipmikes1 commented on apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
> +      disableStorageSelection={!!dbClusterActiveStorage}
Yes, but dbClusterActiveStorage is returned from backend only for mongo so I think that it is unnecessary

2024-01-23 09:41 UTC, filipmikes1 commented on apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
> +      setValue(ScheduleFormFields.storageLocation, {
You mean to check if dbClusterActiveStorage is correct? It is a name that we already selected before and backend is just returning it so I don't think it is necessary

2024-01-23 11:05 UTC, fabio-silva commented on apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
> +      setValue(ScheduleFormFields.storageLocation, {
👍

2024-01-23 11:05 UTC, fabio-silva approved these changes

2024-01-23 11:26 UTC, solovevayaroslavna approved these changes

2024-01-23 11:28 UTC, merged