EVEREST-800-multinamespace-for-monitoring-page
percona/percona-everest-frontend pull request #243
Opened 2024-01-31 10:51 UTC by solovevayaroslavna

![image](https://github.com/percona/percona-everest-frontend/assets/90199600/fec782fe-671f-48dd-a1d0-098dd9aa1ee4)

2024-02-02 13:44 UTC, fabio-silva requested changes

2024-02-02 13:44 UTC, fabio-silva commented on apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
> +          } else return '-';
missing brackets

2024-02-02 13:44 UTC, fabio-silva commented on apps/everest/src/pages/settings/storage-locations/storage-locations.tsx
> +          } else return '-';
brackets

2024-02-02 13:44 UTC, fabio-silva commented on apps/everest/src/components/auto-complete-select-all/auto-complete-select-all.tsx
> +          return [Messages.selectAll as T, ...filtered];
don't quite understand this cast. We accept a generic T, but here we force it to string.
What types of T are we expecting?

2024-02-02 15:14 UTC, solovevayaroslavna commented on apps/everest/src/components/auto-complete-select-all/auto-complete-select-all.tsx
> +          return [Messages.selectAll as T, ...filtered];
in case of namespaces we have options like `["option1", "option2", "option3"... ]`, but we can have options like` [{}, {}]`, so i tried to keep this component universal

I tried to implement an `Array<string|T>` solution
but the `createFilterOptions` function didn't allow me to implement this, it started to conflict with the `params` type

so the main goal was to keep ability to use both Array<string> and Array<object>

2024-02-02 15:16 UTC, solovevayaroslavna commented on apps/everest/src/components/auto-complete-select-all/auto-complete-select-all.tsx
> +          return [Messages.selectAll as T, ...filtered];
I stucked about this error in case of <string|T>
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/87f3d9ed-24d7-4979-9287-3fa24302d6aa)

2024-02-02 15:52 UTC, solovevayaroslavna commented on apps/everest/src/components/auto-complete-select-all/auto-complete-select-all.tsx
> +          return [Messages.selectAll as T, ...filtered];
fixed in https://github.com/percona/percona-everest-frontend/pull/243/commits/28b3545d07f015e7cd72361c8ec806c0e98f45a5

2024-02-06 13:24 UTC, filipmikes1 approved these changes

2024-02-07 10:10 UTC, merged