EVEREST-801 Fix db versions
percona/percona-everest-frontend pull request #250
Opened 2024-02-05 10:29 UTC by filipmikes1

2024-02-06 11:40 UTC, solovevayaroslavna requested changes
can we add a test for this?

2024-02-07 13:34 UTC, filipmikes1 commented
> can we add a test for this?

E2E test added

2024-02-08 10:46 UTC, fabio-silva approved these changes

2024-02-13 15:51 UTC, fabio-silva approved these changes

2024-02-15 11:38 UTC, solovevayaroslavna approved these changes

2024-02-15 11:39 UTC, merged