Draft: EVEREST-835-dbtype-bug-two-namespaces-with-single-operator
percona/percona-everest-frontend pull request #256
Opened 2024-02-12 16:29 UTC by solovevayaroslavna

2024-02-13 05:33 UTC, solovevayaroslavna commented on apps/everest/src/pages/database-form/steps/first/first-step.tsx
> +      if (!dbEngines.find((engine) => engine.type === dbEngine)) {
for situations where user sets one db, then changes namespace, but new namespace hasn't the same db in the operators list, so we need to change selected type to any available

2024-02-14 12:42 UTC, fabio-silva requested changes

2024-02-14 12:42 UTC, fabio-silva commented on apps/everest/src/pages/database-form/steps/first/first-step.tsx
> +        const defaultDbType = dbEngineToDbType(dbEngines[0].type);
this declaration is already present in the first block. Let's move it outside and reuse the const

2024-02-14 13:08 UTC, fabio-silva approved these changes

2024-02-14 13:09 UTC, merged