EVEREST-629 Allowed pitr restore to new db cluster
percona/percona-everest-frontend pull request #266
Opened 2024-02-18 17:42 UTC by filipmikes1

2024-02-21 01:07 UTC, fabio-silva requested changes

2024-02-21 01:07 UTC, fabio-silva commented on apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
> +                pointInTimeDate: pitrBackup!.toISOString().split('.')[0] + 'Z',
Let's do some proper checking before using `!` and accessing `[0]`.
We can create an empty var at the beginning of the code block, do checks and eventually assign it to this expression.

```
let pointInTimeDate = '';

if (pitrBackup && pitrBackup instanceof Date ) {
    pointInTimeDate = pitrBackup.toISOString().split('.')[0] + 'Z';
}
```

2024-02-21 08:52 UTC, filipmikes1 commented on apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
> +                pointInTimeDate: pitrBackup!.toISOString().split('.')[0] + 'Z',
Sure, I just copied it from few lines bellow. I can change it and refactor also old code to properly check it

2024-02-21 15:48 UTC, fabio-silva requested changes

2024-02-21 15:48 UTC, fabio-silva commented on apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
> +          pitr: backupDataSource.pitr && {
```
...(backupDataSource.pitr && {
    pitr: {
        date: backupDataSource.pitr.date,
        type: 'date',
    }
 })
```

2024-02-29 10:34 UTC, solovevayaroslavna reviewed
for me it looks okey, but... do we need a test there?

2024-02-29 10:34 UTC, solovevayaroslavna approved these changes

2024-02-29 11:42 UTC, merged

2024-02-29 11:43 UTC, filipmikes1 commented
> for me it looks okey, but... do we need a test there?

I will merge it. They can be created as a separated task.