EVEREST-862 Add column hide state to local storage
percona/percona-everest-frontend pull request #272
Opened 2024-02-26 15:43 UTC by filipmikes1

EVEREST-862

2024-02-28 14:15 UTC, fabio-silva requested changes

2024-02-28 14:15 UTC, fabio-silva commented on packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
> +export const isObjectEmpty = (obj: object) => Object.keys(obj).length > 0;
if the object is empty, shouldn't length be 0?

2024-02-28 14:15 UTC, fabio-silva commented on packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
> +export const hidePositiveUnnecessaryValues = (
not sure the naming is correct. Doesn't this function only return hidden columns?

2024-02-29 11:55 UTC, filipmikes1 commented on packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
> +export const isObjectEmpty = (obj: object) => Object.keys(obj).length > 0;
True, logic is correctly applied but naming is wrong. Fixed.

2024-02-29 11:56 UTC, filipmikes1 commented on packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
> +export const hidePositiveUnnecessaryValues = (
I mean naming is correct, but your point of view is better. Renamed to filterHiddenColumns

2024-02-29 12:01 UTC, fabio-silva approved these changes

2024-02-29 13:28 UTC, merged