EVEREST-161 storage location page
percona/percona-everest-frontend pull request #45
Opened 2023-08-01 13:44 UTC by filipmikes1

2023-08-03 19:27 UTC, fabio-silva requested changes

2023-08-03 19:27 UTC, fabio-silva commented on apps/everest/components/general-create-edit-modal/dialog-title/dialog-title.tsx
> +import CloseIcon from '@mui/icons-material/Close';
@filipmikes1 we already have a DialogTitle on ui-lib.
Check the example here: https://github.com/percona/percona-everest-frontend/blob/main/apps/everest/pages/new-database/new-database.tsx#L105

2023-08-03 19:27 UTC, fabio-silva commented on apps/everest/hooks/api/backup-storages/__mocks__/useBackupStorages.ts
> +import { StorageType } from '../../../../pages/settings/storage-locations/storage-locations.types';
I think this should be where it was. 
`StorageType` can be used on multiple parts of the app, not just storage location settings.

2023-08-03 19:27 UTC, fabio-silva commented on apps/everest/utils/generalOptimisticDataUpdate.ts
> +        value.id === updatedObject.id ? updatedObject : value
what if there's no `id`, but any other key that identifies the object?

2023-08-04 12:38 UTC, filipmikes1 commented on apps/everest/components/general-create-edit-modal/dialog-title/dialog-title.tsx
> +import CloseIcon from '@mui/icons-material/Close';
Removed

2023-08-04 12:46 UTC, filipmikes1 commented on apps/everest/pages/settings/storage-locations/storage-locations.tsx
> +          open={openCreateEditModal}
I added it there because without the component is always created and unnecessarily re-rendering even if the modal is closed

2023-08-04 12:55 UTC, filipmikes1 commented on apps/everest/utils/generalOptimisticDataUpdate.ts
> +        value.id === updatedObject.id ? updatedObject : value
I think it is a standard practice that every record should have its own ID and if there is a different identifier, developers should be able to implement this functionality manually. This approach allows for quick usage without repeated boilerplate code in most cases and for edge cases developers should implement this functionality manually.

2023-08-04 12:59 UTC, filipmikes1 commented on apps/everest/hooks/api/backup-storages/__mocks__/useBackupStorages.ts
> +import { StorageType } from '../../../../pages/settings/storage-locations/storage-locations.types';
moved

2023-08-04 15:09 UTC, fabio-silva requested changes

2023-08-04 15:09 UTC, fabio-silva commented on apps/everest/pages/settings/storage-locations/storage-locations.tsx
> +        header: Messages.type,
The type should be "Amazon S3" and not "s3", so we need to convert it

2023-08-04 15:09 UTC, fabio-silva commented on apps/everest/pages/settings/storage-locations/storage-locations.tsx
> +            onClick={() => handleOpenCreateModal()}
```suggestion
            onClick={handleOpenCreateModal}
```

2023-08-04 15:09 UTC, fabio-silva commented on apps/everest/pages/settings/storage-locations/storage-locations.tsx
> +              {row.original.url && (
After latest changes, this check is not needed. If the value is not there, the label won't show up automatically

2023-08-04 15:09 UTC, fabio-silva commented on apps/everest/pages/settings/storage-locations/storage-locations.types.ts
> +  .passthrough();
`.passthrough` is not needed here. We had it on DB wizard because it was a multi-step form with different schemas along the way

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.composition.tsx
> +  .passthrough();
same as above

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.docs.mdx
> +A component that is generic create edit modal as a wrapper around form fields to minimize boilerplate.
```suggestion
A component that is a generic create/edit modal as a wrapper around form fields to minimize boilerplate.
```

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.spec.tsx
> +  .passthrough();
same

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.tsx
> +export const CreateEditModal = <T extends FieldValues>({
We should rename this. This modal can be any dialog with a form, not just meant for create/edit.
Something along "FormDialog" or "FormModal".

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.tsx
> +      <DialogTitle id="dialog-title" onClose={closeModal}>
what is this id?

2023-08-04 15:09 UTC, fabio-silva commented on ui-lib/form/create-edit-modal/create-edit-modal.types.ts
> +export interface DialogTitleProps {
Are we using this?

2023-08-04 15:09 UTC, fabio-silva commented on apps/everest/pages/settings/storage-locations/storage-locations.types.ts
> +  id?: string;
why is id optional?

2023-08-07 16:00 UTC, filipmikes1 commented on apps/everest/pages/settings/storage-locations/storage-locations.tsx
> +        header: Messages.type,
Good catch, added mapper 👍

2023-08-07 16:01 UTC, filipmikes1 commented on ui-lib/form/create-edit-modal/create-edit-modal.tsx
> +export const CreateEditModal = <T extends FieldValues>({
renamed to FormDialog

2023-08-07 16:03 UTC, filipmikes1 commented on ui-lib/form/create-edit-modal/create-edit-modal.types.ts
> +export interface DialogTitleProps {
No, we both implemented the same dialogTitle at the same time, this is the remainder. Removed.

2023-08-07 16:05 UTC, filipmikes1 commented on apps/everest/pages/settings/storage-locations/storage-locations.types.ts
> +  id?: string;
Because before BackupStorage creation is id not set yet.

2023-08-07 17:56 UTC, fabio-silva approved these changes

2023-08-09 05:31 UTC, solovevayaroslavna approved these changes

2023-08-09 13:46 UTC, merged