Everest 194 db clusters actions
percona/percona-everest-frontend pull request #53
Opened 2023-08-10 09:17 UTC by solovevayaroslavna

2023-08-10 09:17 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-everest-frontend?pullRequest=53) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-everest-frontend?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-everest-frontend?pullRequest=53) it.</sub>

2023-08-10 10:25 UTC, fabio-silva requested changes

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        debugger;
debugger

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        if (dbClusterName) {
I think we should check `dbCluster` instead, which comes from `find`

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +              reFetchDbClusters(); // TODO change to the common function when  EVEREST-161-storage-location-page will be ready
Will we change this to optimistic updates as well?

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/components/db-cluster-view/dbClusterView.messages.ts
> +    noData: "You don't have any db-cluster yet. Create one to get started.",
maybe without slash? and "DB", uppercase

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/contexts/db-cluster/db-cluster.context.tsx
> +  const [dbClusterName, setDbClusterName] = useState<string>('');
What if we pass the actual DB cluster object, instead of just the name?

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/pages/database-form/steps/first/first-step.tsx
>    }, [dbType, dbEngines]);
should `mode` be here?

2023-08-10 10:25 UTC, fabio-silva commented on apps/everest/pages/database-form/steps/sixth/sixth-step.messages.ts
> +  goToList: 'Go to list of my db-cluster',
same as before

2023-08-10 12:18 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +              reFetchDbClusters(); // TODO change to the common function when  EVEREST-161-storage-location-page will be ready
yes, i'm working on it

2023-08-10 12:20 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/dbClusterView.messages.ts
> +    noData: "You don't have any db-cluster yet. Create one to get started.",
I'm sorry, it seems at that time I had the wrong layout, now the text "databases" is on the layouts

2023-08-10 12:23 UTC, solovevayaroslavna commented on apps/everest/contexts/db-cluster/db-cluster.context.tsx
> +  const [dbClusterName, setDbClusterName] = useState<string>('');
we can, what do you think... should we do the request for this cluster to get the last version of information or we can use one from the list? Becouse we can add object to context and use this object...

2023-08-14 05:01 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        if (dbClusterName) {
@filipmikes1 becouse of this in apps/everest/pages/database-form/database-form.tsx
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/549f0fe5-1783-41d0-bd2f-c0f11815e0ed)

If I leave the previous value in the form, then the form uses it first when reloading

2023-08-14 09:41 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +                  setSelectedDBClusterName(row.original.databaseName!);
thanks! fixed

2023-08-14 09:43 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        const paused = !isPaused(status);
becouse I need change value from paused to resume and vise versa, so if current state is paused/pausing => then during click i need to reverse it. It's boolean value

2023-08-14 09:47 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        const dbCluster = combinedDbClusters.find(item => item.metadata.name===dbClusterName);
No( row original loose a lot of information, it uses just data which we need for table rows, but for editing/paused/resume we should use the same full object that we had

2023-08-15 14:31 UTC, filipmikes1 commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        const paused = !isPaused(status);
Okay then some better naming should be here, this is a little misleading. Or some explanatory commend.

2023-08-15 14:33 UTC, filipmikes1 commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        if (dbClusterName) {
Then I would expect `(status: DbClusterStatus, dbClusterName:string)` to be `(status: DbClusterStatus, dbClusterName:string | undefined)` because now type is set different then it is in run time.

2023-08-16 07:31 UTC, solovevayaroslavna commented on apps/everest/contexts/db-cluster/db-cluster.context.tsx
> +  const [dbClusterName, setDbClusterName] = useState<string>('');
fixed to <Link state/>

2023-08-16 07:33 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        const paused = !isPaused(status);
fixed to https://github.com/percona/percona-everest-frontend/pull/53/commits/bfe6d12b287c5af1396fe93cbcf8b8fb9f484b41#:~:text=shouldBePaused%20%3D%20!isPaused(status)%3B

2023-08-16 07:34 UTC, solovevayaroslavna commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +        const paused = !isPaused(status);
![image](https://github.com/percona/percona-everest-frontend/assets/90199600/4e835186-8062-4d78-8ba5-1a0fe0fcdc77)

2023-08-16 13:35 UTC, filipmikes1 approved these changes

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/steps/second/second-step.utils.ts
> +  const memory = +removeMeasurementValue(resources?.memory.toString());
Typescript is complaining, there should be check for resources to be available.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/steps/second/second-step.utils.ts
> +      item.cpu === +resources?.cpu &&
Same here

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
> +  [DbWizardFormFields.cpu]: +dbCluster?.spec?.engine?.resources?.cpu || 0,
Also here is typescript complainig. You can't parse string to number with possible undefined value.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
> +    dbCluster?.spec?.engine?.resources?.memory.toString()
Also typescript complains.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
> +  return { defaultValues, dbClusterData: data, dbClusterStatus: status };
Same here. Data can be undefined.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
> +      : { [DbWizardFormFields.dbVersion]: '' }
Also typescript error. You can't pass just dbVersion without other values.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/components/db-cluster-view/DbClusterView.tsx
> +                        (oldData?: ExtraDbCluster[]) => oldData.map(value => value.dbCluster.metadata.name === updatedObject.metadata.name ? {
Also typescript error oldData can be undefined.

2023-08-22 11:41 UTC, filipmikes1 commented on apps/everest/pages/database-form/steps/second/second-step.utils.ts
> +export const removeMeasurementValue = (value: string) =>
What is exact purpose of this function?

2023-08-22 15:27 UTC, fabio-silva approved these changes

2023-08-23 05:52 UTC, solovevayaroslavna commented on apps/everest/pages/database-form/steps/second/second-step.utils.ts
> +export const removeMeasurementValue = (value: string) =>
we have from BE strings "2G" "1G" etc... so this function deletes G and returns number value

2023-08-23 08:06 UTC, merged