EVEREST-318 disable hiding for first 2 columns
percona/percona-everest-frontend pull request #89
Opened 2023-09-14 12:11 UTC by filipmikes1

2023-09-15 14:06 UTC, fabio-silva requested changes

2023-09-15 14:06 UTC, fabio-silva commented on ui-lib/table/table.tsx
> +      return { ...col, enableHiding: false };
can't this be done on the column definition itself?

2023-09-18 08:09 UTC, filipmikes1 commented on ui-lib/table/table.tsx
> +      return { ...col, enableHiding: false };
Yes, it can, but Nuna said this should be the default behavior for all tables. So I added it here so we don't need to think about it. But we can still discuss this.

2023-09-18 10:10 UTC, fabio-silva approved these changes

2023-09-19 09:53 UTC, merged